[platformio]
default_envs = nando_s3_uart

[env:nando_s3_uart]
platform = espressif32@6.12.0
board = esp32-s3-devkitc-1
framework = arduino
; Perfil provisional para la placa fotografiada N16R8. No activa PSRAM.
; DIO a 80 MHz y partición de 4 MB: no dependemos de toda la memoria anunciada.
board_build.flash_mode = dio
board_build.f_flash = 80000000L
board_upload.flash_size = 4MB
board_build.partitions = default.csv
build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=0
    -D CONFIG_BT_NIMBLE_MAX_CONNECTIONS=1
monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0
upload_speed = 115200
lib_deps =
    h2zero/NimBLE-Arduino@2.3.6
    adafruit/Adafruit INA219@1.2.3
    adafruit/Adafruit BusIO@1.17.4
